# Homework 3

**Due Date**: July 4

## Task 1: The Model:

a) From line 14 in the template you and the PTDF matrix of the network. Explain
what the PTDF matrix does, what assumptions and information is used to derive
it.

The power transfer distribution factors (PTDF) matrix gives the node-line sensitivity of the modelled power network. These sensitivities explain how power flows change if power injection between nodes is shifted, resulting in different line flows. The actual power flow in the modelled network is nonlinear and can be simplified and approximated by the DC load flow model given some assumptions. 
Specifically, the following assumptions are made (EW-MOD lecture, 28.05.2018, slide 8):
 - No reactive power flows, i.e. only consider active power
 - No active power losses 
 - Small Voltage angles 
 - Flat voltage profile / equal voltage amplitude all nodes

To derive the PTDF matrix, we need to know the the incidence matrix, describing which nodes are connected to which lines and each line's susceptance. Unfortunately, the PTDF for equation for nodal balance is linear dependent and results in a non-invertible matrix. We thus work with a reduced incidence matrix by defining a slack node. This slack node is removed from the incidence matrix and assumed to balance all other grid injections. Its PTDF values are set to zero, meaning that changing its net injection will not affect line flows. The PTDF can then be derived as a product of the Line Susceptance Matrix and the inverse of the Node Susceptance Matrix.

b) Describe the Objective function of the problem and distinguish the different sub-
sets of nodes.

The objective function maximizes total welfare, which is the sum of consumer (demand) and producer (supply) surplus. Since producer's revenues represent costs to consumers, the maximization problem can be reduced to the difference between gross consumer surplus and total costs.  
Ehrenmann and Smeers choose symmetric demand and marginal cost function that include a linear (a) and quadratic (b) term. 

Generators are located at node 1, 2 and 4 and consumers at nodes 3, 5 and 6. Node 6 is defined as slack node. 

c) State the problem type and an available solver to solve it.
The problem we are faced with is a quadratic problem. We therefore chose the IpoptSolver from the open source package Ipopt to solve it. The non-differentiation between linear and quadratic solvers on https://www.juliaopt.org/ is not very useful since it falsely suggests that linear solvers like Clp or Cbc can also deal with quadratic problems.

d) The model formulation in the template is different to formulation in the paper.
Explain why both formulations are equivalent and describe possible benefits of either.

The model formulation in the template differentiate between demand and supply quantities for each node and each nodes net injection. Consequently, the first constraint describes the nodel Energy balance, according to which generation and consumption at each node must equal its net injection. The second constraint relates to the balancing character of the slack node, whose net injection must balance the sum of all other nodes' net injections. In constrast, Ehrenmann and Smeers do not explicitly model net injection at each node. Instead, they incorporate only electricity quantities for producer and consumer nodes, q_i. The constraint for their slack node simply states that the overall quantity of electricity must be zero, i.e. that generation must equal demand.

Both formulations are equal because nodes are strictly devided into producers and consumer nodes. This means that the quantities consumed/produced at a node equal its (negative) net injection by definition. Though the formulation of Ehrenmann and Smeers might be more intuitive for an microeconomic perspective, explicitly defining net injections for each node has the advantage that the model can easily be extended to nodes incorporating both consumers and producers. Furthermore, it easily allows to get nodal prices as dual variables on the energy balance of each node.

e) How is the market price defined in the model and how are supply nodes distin-
guished from demand nodes?

The market price is defined as the inversed demand function (demand nodes) or as the marginal costs function (supply nodes) depending on the electricity quantity. Demand and supply nodes can be distinguished by indexing the electricity demand either on DEM_NODES or SUP_NODES.

f) Use the result Dictionary to get access the model results and return all values which
are used in the result table in the paper plus the price by dual as a reference.

results["objective"]    = getobjectivevalue(Ehrenmann)
results["quantity"]     = NamedArray(getvalue(Q).innerArray)
results["netinjection"] = NamedArray(getvalue(INJ).innerArray)
results["flows"]        = ptdf_array*results["netinjection"]
results["prices"]       = NamedArray(getdual(EnergyBalance).innerArray)

price: 35 in all nodes -> in constrast to Smeers, p. 18!
quantities (node 1,2,3,4,5,6): 500, 400, 50, 0, 400, 450
flows on lines ("1-3","1-2","2-3","1-6","2-5","5-6","4-5","4-6"):
38.54,27.085,-11.46,434.375,415.625, 10.415,5.21,  5.21

-> there is a mistake! order of line is different (why has node 4 no inflows but outflows though quantity is zero)?

g) Run the template. To which result from the paper does this problem formulation
correspond?

This corresponds to the one zone setup of displayed in "Table 10: One Zone" on page 18. We have the same nodal price since we do not impose any capacity constraints on lines. 


### Task 2: Equations and Results:
a) Based on the results of the template model, will this market price be equal to
the dual on the Energy Balance. Explain possible differences in terms of the
formulation or optimization problems in general.

-> this is probably the reason for price difference with Smeers

b) Implement two constraints which enforce upper- and lower limits in line flows.
Make sure this constraint only applies to the lines "1-6" and "2-5". This should
correspond to the results from Table 4. Explain why the market- and dual price
are now equivalent.

c) Implement a constraint that forces the market prices to be equal to a variable
price for all nodes within a price zone. You can use a similar approach as in the
plants-in-zone dictionary from the transport model.

d) Use this constraint to implement configurations 2.1 and 2.2 from the paper. Confirm the results with Tables 11 and 12. Compare the resulting prices from the
definition and the ones by the dual.