# Homework 2

**Due Date**: May 28

## Task 1

a) Describe how information regarding technology and location of power plants is
implemented in the model and how, meaning with what syntax, you can access it.

Information on technology and location of power plants is fed into the model from external data that is imported from several csv files. All of these data set are load into tables, from which certain columns/rows are selected and stored in dictonaries. The information regarding technology and location of power plants is then fed into model via the dictionary "sets", which contains multiple dictionaries.

We can access information in dictonaries via indexing. For example, for inquire the technology of a given plant (P5) from the "TECH_PLANTS" dictionary, we can write 
TECH_PLANTS["P5"]. 

To find all Biomass plants within "sets" we can write 

sets["Plant_Tech"]["Biomass"]

b) 
PLANTS: Array of strings containing name of each plant
DISP: Array of strings containing name of of the subset of dispatchable plants
NONDISP: Array of strings containing name of of the subset of non-dispatchable plants
CON: Array of strings containing name of of the subset of conventional plants
RES: Array of strings containing name of of the subset of renewable plants

- Last four are all subsets of PLANTS, with DIS & NONDISP as well as CON & RES being complements. Plants are devided into  DIS and NONDISP based on dispatchability, whereas CON and RES refers to conventional and renwable plants. Differences occur due to Biomass plants, which are included in RES but are dispatchable and thus also belong to DISP.

Distinction is useful to set up constraints and objective function properly. In the objective function we minimize the sum of total costs incurred by dispatchable power plants (with nonzero marginal costs), whereas nondispatchables are not considered due to their zero marginal costs. To evaluate power generation profiles from renewables, it is useful to dinstinguish between RES and CON.

c) To calculate zonal generations, information on the zonal availability (availability), the technology type of each plant (TECH_PLANTS), maximum generation of each plant (g_max), a list of all pv and wind plants (NONDISP), as well as the location of each power plant (ZONE_PLANTS) is necessary. Based on this input, RES generation is calculated for each RES plant on an hourly basis and stored in the array g_res. This RES generation is later fed into the model as a parameter.

## Task 2
We need to add exchange variable EX, which is positive 

@variables transport_problem begin
            G[DISP, HOUR] >= 0
            G_RES[NONDISP, HOUR] >= 0
            G_stor[STOR, HOUR] >= 0 #generation from storage
            L[STOR, HOUR] >= 0 #current storage level
            D_stor[STOR, HOUR] >= 0 #consumption from storage
            EX[ZONES, ZONES, HOUR] >= 0 #Exchange between zones
            

Add constraint to account for zonal exchange and zonal energy balance, including all generation types

@constraint(transport_problem, Market_Clearing[zone=ZONES, hour=HOUR],
                     sum(G[disp, hour] for disp in intersect(DISP , PLANT_ZONE[zone]))
                   + sum(G_RES[nondisp, hour] for nondisp in intersect(NONDISP , PLANT_ZONE[zone]))
                   + sum(G_stor[stor, hour] for stor in intersect(STOR , STOR_ZONE[zone]))
                    ==
                    demand[hour, zone]
                   - sum(EX[from_zone, zone, hour] for from_zone in ZONES)
                   + sum(EX[zone, to_zone, hour] for to_zone in ZONES)
                   + sum(D_stor[stor, hour] for stor in intersect(STOR , STOR_ZONE[zone])))
            
c)             
To account for the transmission constraints between the zones, we add the NTC constraint

    @constraint(transport_problem, NTC[to_zone=ZONES, from_zone=ZONES,hour=HOUR],
            EX[from_zone, to_zone, hour] <= ntc[from_zone, to_zone]);
            
            
## Task 3

a) Set ntc to zero via 

ntc *= 0 , no exchange between zones possible
large price differences since differing marginal technologies
highest (constant) price in south, since natural gas always marginal technology
high price volatility especially in north due to lack of storages

b)
one price for all zones, if this was not the case, solution could be improved via trading


c)
#north: in 50% case, more curtailment of wind -> access supply cannot be stored/transmitted
#south: in 50% case load is almost exclusively served by domestice generattion, whereas some gas is substituted with increased transmission capacities

in all cases: price(s) are volatile and increase in times of peak load. when transmissions constraints bind, market splitting occurs.
3a: four separate market, prices very volatile
3b: one integrated market, price is least volatile compared to other scenarios
3c50%: in times where transmission constraints bind, we see up to 4 different prices (market splitting), whereas at some points in time up to three zones (north, west, east) form one market with one price 
3c100%: similar patterns as in 3c50%%. market splitting is less frequent due to higher transmission capacity. price is slighlty less volatile compared to 3c50%.


d)
Energy-Only Market: Market design where only energy is traded and power generators get compensated only for the power they actually produce. Other services like providing balancing capacity are not rewarded.
The model at hand represents a energy-only market since only energy is traded, only energy generation costs are minimized and the energy price is determined by aggregate supply (merit order) and demand (and possible line congestions). The capacity market is not modelled and peak load power plants, like the gas plants in 3b, would not receive compensation for their capacity provision.

Market Coupling: Mechanism of connecting two or more neighbouring power markets with means of cross-border interconnectors such that the overall economic wellfare is increased due to market integration. If prelimimary settlement of power markets lead to different market prices in neighbouring countries (zones), electricity can be traded between the two zones such that the overall efficiency is increased and the price difference decreases. Following the interpretation of Ehrenmann and Smeers (2004, p. 23), we can represent market coupling  by assuming that the of settled power price in the market of each zone takes is a function of its net imports. Based on these inverse demand functions, the energy trade between zones is settled on an interzonal market.

--> Though transport model contains different zones and transmission constraint, it would be more appropriate to represent Market coupling in two-step clearing process. First, each zone`s energy balance should be preliminarily cleared. Then inter-zonal trading can be admitted. 


Market Splitting: Mechanism of deviding a single power market (zone) into two or more zones due to lack of intra-line capacity, resulting in line congestion. The subzones resulting from market splitting will have different prices. This can be seen in 3c, where market splitting between two or more zones occurs temporarily as line congestion occurs. As explained by Ehrenmann and Smeers (2004, p. 16), the zones resulting from market splitting can be fixed or variable, while we see the latter in our transport model.

#Explain how these concepts are represented in the model and if not,
#what additional constraints/representations are missing. Refer to the paper by
# Ehrenmann and Smeers.

-- whatelse??
