# Homework 4

**Due Date**: July 24

## Task 1: Expand the model:

The cost parameters we use represent a 2050 perspective and are taken from @pape2014roadmap and @energiewende2014stromspeicher. These sources have been used in dispatch and investment modelling for storage analysis for example in @zerrahn2015greenfield. Additionally to the pumped-hydro storage, a mid-term storage option, we include a short-term storage technology, lithium-ion batteries, and a long-term option, and power-to-gas. 
Following @zerrahn2015greenfield, we assume a 22,5 lifetime for pumped-hydro storage (mean of electrolysis and reconversion lifetime).

b) 
Our csv input file ocntains the following parameters:

technology	oc_power	oc_storage	lifetime	efficiency
PSP	  1100000	  10000	80	    0.8
LITH	35000  	 150000	20	    0.92
P2G	  1700000    	200	22,5	0.38

We calculate annuity via 

annuity_oc_power = map(row-> row.oc_power * (i+1)^row.lifetime / (((1+i)^row.lifetime)-1), storage_table)
annuity_oc_energy = map(row-> row.oc_storage * (i+1)^row.lifetime / (((1+i)^row.lifetime)-1), storage_table)

In order to avoid a double charge for an investment into storages, we change the objective function to 

    @objective(Invest, Min,

        sum(mc[tech] * G[hour,tech] * 8760/length(HOUR) for tech in TECHNOLOGY, hour in HOUR)

        + sum(annuity[tech] * CAP[tech] for tech in TECHNOLOGY)
        + 0.5 * sum(annuity_oc_power[stor] * CAP_ST[stor] for stor in STOR)
        + 0.5 * sum(annuity_oc_energy[stor] * CAP_ST[stor] for stor in STOR) )


c) Run the model for shares of 70 %, 80 %, 90 %, and 100 %. Submit a plot from
the given model and one plot after you successfully implemented storages. How
does the investment into generation capacity change? What happens with the
curtailment?

- gas capacity decreases with storage for all RES shares
- largest different for 100% scenarios, capacity of onshore an offshore wind decreased strongly thorugh storage capacity
- in storage scenarios, more pv and onshore wind is installed with higher RES share
- For all modelled RES shares, the resulting curtailment is lower in the storage scenario compared to the no-storage case. Furthermore, curtailment in the storage scenario is drastically lower in the high RES scenarios. For the 100% RES scenario, it decreases more than 3 orders of magnitude (from 10763.3 TWh to 5.5 TWh). This is because the excess energy can be stored for later use instead of being curtailed. 


d) Create your own plot showing the investment into storage power and storage ca-
pacity. How much energy is stored during the course of the year? How much
energy was lost due to storage efficiency?

The installed storage power capacity increase with higher shares of RES, whereas the energy capacity is rather the same and even decreasing for the case of P2G. This is because more lithium-ion batteries are installed in the higher RES scenarios, since more PV is installed. We can see clear differences in investment structure between storage technologies, characterized by E/P ratio, which gives the relationship between the energy and power capacity fo a storage. Lithium-ion batteries, as typical short-term storage, has the smallest E/P ratio. In constrast, P2G has a very large E/P ratio since it is used a long-term storage.

The overall stored energy over the year increases with the shared of RES, from a total of 130TWh for 70% RES to more than 500TWh fpr the 100% RES case. The distribution over the different storage technologies can be seen in plot XXX:
Similarily, the lost energy increases with higher RES share since it is a linear function of the storage energy. As can be seen in plot YYY, a total of roughly 80TWh is lost for the 100% scenario.


Sources

@article{energiewende2014stromspeicher,
  title={Stromspeicher in der Energiewende-Untersuchung zum Bedarf an neuen Stromspeichern in Deutschland f{\"u}r den Erzeugungsausgleich, Systemdienst-leistungen und im Verteilnetz},
  author={Energiewende, Agora},
  journal={Berlin, Sep},
  year={2014}
}


@article{pape2014roadmap,
  title={Roadmap Speicher-Bestimmung des Speicherbedarfs in Deutschland im europ{\"a}ischen Kontext und Ableitung von technisch-{\"o}konomischen sowie rechtlichen Handlungsempfehlungen f{\"u}r die Speicherf{\"o}rderung},
  author={Pape, Carsten and Gerhardt, Norman and H{\"a}rtel, Philipp and Scholz, Angela and Schwinn, Rainer and Drees, Tim and Maaz, Andreas and Sprey, Jens and Breuer, Christopher and Moser, Albert and others},
  journal={Fraunhofer IWES, Kassel},
  year={2014}
}

@article{zerrahn2015greenfield,
  title={A Greenfield model to evaluate long-run power storage requirements for high shares of renewables},
  author={Zerrahn, Alexander and Schill, Wolf-Peter},
  year={2015}
}

